exclude_projects = []

[workspace]
name = "code-explorer"
discovery_max_depth = 3

[resources]
max_lsp_clients = 5
idle_timeout_secs = 600

[[project]]
id = "code-explorer"
root = "."
languages = ["rust"]
depends_on = []

[[project]]
id = "java-library"
root = "tests/fixtures/java-library"
languages = [
    "kotlin",
    "java",
]
depends_on = []

[[project]]
id = "kotlin-library"
root = "tests/fixtures/kotlin-library"
languages = [
    "kotlin",
    "java",
]
depends_on = []

[[project]]
id = "python-library"
root = "tests/fixtures/python-library"
languages = ["python"]
depends_on = []

[[project]]
id = "rust-library"
root = "tests/fixtures/rust-library"
languages = ["rust"]
depends_on = []

[[project]]
id = "typescript-library"
root = "tests/fixtures/typescript-library"
languages = [
    "typescript",
    "javascript",
]
depends_on = []
